[package]
name = "gocardless-unofficial"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
secrecy = "0.8.0"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
